# Generated by Django 6.0.4 on 2026-04-28 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "opis_id",
                    models.IntegerField(
                        db_column="OPIS Truckstop ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(db_column="Truckstop Name")),
                ("address", models.TextField(db_column="Address")),
                ("city", models.TextField(db_column="City")),
                ("state", models.TextField(db_column="State")),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
            options={
                "verbose_name": "Station",
                "verbose_name_plural": "Stations",
                "db_table": "stations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FuelPrice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rack_id", models.IntegerField(db_column="Rack ID")),
                (
                    "retail_price",
                    models.DecimalField(
                        db_column="Retail Price",
                        decimal_places=3,
                        max_digits=6,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        db_column="OPIS Truckstop ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_prices",
                        to="optimizer.station",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fuel Price",
                "verbose_name_plural": "Fuel Prices",
                "db_table": "fuel_prices",
                "managed": False,
            },
        ),
    ]
