from django.db import migrations

CREATE_STATIONS_SQL = """
CREATE TABLE IF NOT EXISTS stations (
    "OPIS Truckstop ID" integer PRIMARY KEY,
    "Truckstop Name" text NOT NULL,
    "Address" text NOT NULL,
    "City" text NOT NULL,
    "State" text NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL
);
"""

CREATE_FUEL_PRICES_SQL = """
CREATE TABLE IF NOT EXISTS fuel_prices (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OPIS Truckstop ID" integer NOT NULL
        REFERENCES stations("OPIS Truckstop ID")
        ON DELETE CASCADE,
    "Rack ID" integer NOT NULL,
    "Retail Price" numeric(6, 3) NOT NULL
);
"""

CREATE_INDEX_SQL = """
CREATE INDEX IF NOT EXISTS idx_fuel_opis_price
ON fuel_prices ("OPIS Truckstop ID", "Retail Price");
"""


def create_optimizer_tables(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(CREATE_STATIONS_SQL)
        cursor.execute(CREATE_FUEL_PRICES_SQL)
        cursor.execute(CREATE_INDEX_SQL)


class Migration(migrations.Migration):
    dependencies = [
        ("optimizer", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_optimizer_tables, migrations.RunPython.noop),
    ]
